src: ../src
dest: ../build
ignore: '**/.DS_Store'

watch:
  paths:
    '${source}/**/*': true
    '../templates/**/*': '**/*.md'
    '${source}/**/*.styl': '**/*'
    '${source}/_assets/**/*': '**/*'
  livereload: true

layouts:
  engine: handlebars
  directory: ../templates/layouts

helpers:
  directory: ../templates/helpers

partials:
  directory: ../templates/partials

inPlace:
  engine: handlebars
  partials: ../templates/partials

autotoc:
  selector: h2, h3

pathCollector:
  debug: false
  groups:
    - key: getting-started
      name: Getting Started
      pattern: ^getting-started/.+\.md$
    - key: features
      name: Feature Walkthroughs
      pattern: ^features/.+\.md$
    - key: accessories
      name: Accessories
      pattern: ^accessories/.+\.md$
    - key: node-red
      name: Node-RED
      pattern: ^node-red/.+\.md$
    - key: everything-else
      name: Everything Else
      pattern: ^everything-else/.+\.md$  
    - key: help
      name: Having Problems?
      pattern: ^help/.+\.md$

permalinks:
  pattern: :coll_key/:id

relativeRoots:
  debug: false
  fixPermalinks: true
  indexFilename: index.md

index: 'getting-started/intro/'

lint:
  files:
    - 'src/**/*.md'
  rules:
    - slug: caps-bean
      regex: '\sbean\s'
      message: 'Always capitalize Bean'
    - slug: caps-lb
      regex: '\slightblue|Lightblue\s'
      message: 'Always capitalize LightBlue'
    - slug: one-word-lb
      regex: '\blight blue\b'
      flags: 'i'
      message: 'LightBlue is one word, not two'
    - slug: two-words-pt
      regex: '\sPunchThrough\s'
      flags: 'i'
      message: 'Punch Through is two words, not one'
    - slug: pt-not-ptd
      regex: '\bPunch Through Design\b'
      flags: 'i'
      message: 'Instead of "Punch Through Design", prefer "Punch Through"'
    - slug: os-x-not-osx
      regex: '\bOSX\b'
      message: 'Instead of "OSX", use "OS X"'
    - slug: no-abs-links
      regex: '\]\(\//'
      message: 'Do not use absolute links'
