src: ../src
dest: ../build
ignore: '**/.DS_Store'

layouts:
  engine: handlebars
  directory: ../templates/layouts

helpers:
  directory: ../templates/helpers

partials:
  directory: ../templates/partials

inPlace:
  engine: handlebars
  partials: ../templates/partials

autotoc:
  selector: h2, h3

pathCollector:
  debug: false
  groups:
    - key: getting-started
      name: Getting Started
      pattern: ^getting-started/.+\.md$
    - key: features
      name: Feature Walkthroughs
      pattern: ^features/.+\.md$
    - key: accessories
      name: Accessories
      pattern: ^accessories/.+\.md$
    - key: platforms
      name: Other Platforms
      pattern: ^platforms/.+\.md$

permalinks:
  pattern: :coll_key/:id

relativeRoots:
  debug: false
  fixPermalinks: true
  indexFilename: index.md

redirect:
  '/': 'getting-started/intro/'
