src: ../src
dest: ../build
ignore: '**/.DS_Store'

watch:
  paths:
    '${source}/**/*': true
    '../templates/**/*': '**/*.md'
    '${source}/**/*.styl': '**/*'
    '${source}/_assets/**/*': '**/*'
  livereload: true

layouts:
  engine: handlebars
  directory: ../templates/layouts

helpers:
  directory: ../templates/helpers

partials:
  directory: ../templates/partials

inPlace:
  engine: handlebars
  partials: ../templates/partials

autotoc:
  selector: h2, h3

pathCollector:
  debug: false
  groups:
    - key: getting-started
      name: Getting Started
      pattern: ^getting-started/.+\.md$
    - key: features
      name: Feature Walkthroughs
      pattern: ^features/.+\.md$
    - key: accessories
      name: Accessories
      pattern: ^accessories/.+\.md$
    - key: node-red
      name: Node-RED
      pattern: ^node-red/.+\.md$
    - key: everything-else
      name: Everything Else
      pattern: ^everything-else/.+\.md$  
    - key: help
      name: Having Problems?
      pattern: ^help/.+\.md$

permalinks:
  pattern: :coll_key/:id

relativeRoots:
  debug: false
  fixPermalinks: true
  indexFilename: index.md

index: 'getting-started/intro/'

lint:
  files:
    - '**/*.md'
  rules:
    - pattern: !!js/regexp /\wbean\w/
      message: 'Always capitalize Bean'
    - pattern: !!js/regexp /\wlightblue|Lightblue\w/
      message: 'Always capitalize LightBlue'
    - pattern: !!js/regexp /\blight blue\b/i
      message: 'LightBlue is one word, not two'
    - pattern: !!js/regexp /\bthe beans?\b/i
      message: 'Instead of "the Bean", prefer simply "Bean"'
