src: ../src
dest: ../build
ignore: '**/.DS_Store'

layouts:
  engine: handlebars
  directory: ../templates/layouts

helpers:
  directory: ../templates/helpers

partials:
  directory: ../templates/partials

inPlace:
  engine: handlebars
  partials: ../templates/partials

autotoc:
  selector: h2, h3

pathCollector:
  - key: features
    name: Feature Walkthroughs
    pattern: ^features/.+.md$

permalinks:
  pattern: :coll_key/:id

relativeRoots:
  debug: true
  fixPermalinks: true
  indexFilename: index.md
