src: ../src
dest: ../build
ignore: '**/.DS_Store'

watch:
  paths:
    '${source}/**/*': true
    '../templates/**/*': '**/*.md'
    '${source}/**/*.styl': '**/*'
    '${source}  /_assets/**/*': '**/*'
  livereload: true

layouts:
  engine: handlebars
  directory: ../templates/layouts

helpers:
  directory: ../templates/helpers

partials:
  directory: ../templates/partials

inPlace:
  engine: handlebars
  partials: ../templates/partials

autotoc:
  selector: h2, h3

pathCollector:
  debug: false
  guides:  # Sidebar links for the guides site
    - key: getting-started
      name: Getting Started
      pattern: ^guides/getting-started/.+\.md$
    - key: features
      name: Feature Walkthroughs
      pattern: ^guides/features/.+\.md$
    - key: node-sdk
      name: Node.js SDK/CLI
      pattern: ^guides/node-sdk/.+\.md$
    - key: node-red
      name: Node-RED
      pattern: ^guides/node-red/.+\.md$
    - key: building-an-app
      name: Building an App
      pattern: ^guides/building-an-app/.+\.md$
    - key: everything-else
      name: Everything Else
      pattern: ^guides/everything-else/.+\.md$
    - key: help
      name: Having Problems?
      pattern: ^guides/help/.+\.md$
  projects:  # Sidebar links for the projects section
    - key: projects
      name: Projects
      pattern: ^example-projects/projects/.+\.md$

permalinks:
  pattern: :coll_key/:id

relativeRoots:
  debug: false
  fixPermalinks: true
  indexFilename: index.md

guides_index: 'getting-started/intro/'
projects_index: 'projects/overview/'

lint:
  files:
    - 'src/**/*.md'
  rules:
    - slug: caps-bean
      regex: '\sbean\s'
      message: 'Always capitalize Bean'
    - slug: caps-lb
      regex: '\slightblue|Lightblue\s'
      message: 'Always capitalize LightBlue'
    - slug: one-word-lb
      regex: '\blight blue\b'
      flags: 'i'
      message: 'LightBlue is one word, not two'
    - slug: two-words-pt
      regex: '\sPunchThrough\s'
      flags: 'i'
      message: 'Punch Through is two words, not one'
    - slug: pt-not-ptd
      regex: '\bPunch Through Design\b'
      flags: 'i'
      message: 'Instead of "Punch Through Design", prefer "Punch Through"'
    - slug: os-x-not-osx
      regex: '\sOSX\s'
      message: 'Instead of "OSX", use "OS X"'
    - slug: no-abs-links
      regex: '\]\(\//'
      message: 'Do not use absolute links'
    - slug: line-nums-bold
      regex: '\*\s+`Line'
      message: 'Use **bold** instead of `code` for discussing line numbers of code blocks'
    - slug: bl-for-win
      regex: '\bWindows Bean Loader\b'
      flags: 'i'
      message: 'Use "Bean Loader for Windows", not "Windows Bean Loader"'
    - slug: no-dash-gt-arrows
      regex: '\s->\s'
      flags: 'i'
      message: 'Use "&rarr;" instead of "->"'
    - slug: no-dash-lt-arrows
      regex: '\s<-\s'
      flags: 'i'
      message: 'Use "&larr;" instead of "<-"'
