'use strict'

let Metalsmith = require('metalsmith')
let Yaml = require('js-yaml')
let fs = require('fs')

let Metadata = require('./plugins/metadata')
let PathCollector = require('./plugins/path-collector')
let RelativeRoots = require('./plugins/relative-roots')

let Markdown = require('metalsmith-markdown')
let Layouts = require('metalsmith-layouts')
let AutoTOC = require('metalsmith-autotoc')
let Helpers = require('metalsmith-register-helpers')
let Partials = require('metalsmith-register-partials')
let Permalinks = require('metalsmith-permalinks')
let Ignore = require('metalsmith-ignore')
let Stylus = require('metalsmith-stylus')
let InPlace = require('metalsmith-in-place')
let Paths = require('metalsmith-paths')

const config = Yaml.load(fs.readFileSync('config.yml', 'utf8'))

module.exports =
  Metalsmith(__dirname)
  .source(config.src)
  .destination(config.dest)
  .use(Metadata({config: config}))
  .use(PathCollector(config.pathCollector))
  .use(Paths())
  .use(Ignore(config.ignore))
  .use(RelativeRoots(config.relativeRoots))
  .use(Partials(config.partials))
  .use(Helpers(config.helpers))
  .use(InPlace(config.inPlace))
  .use(Markdown())
  .use(Stylus())
  .use(AutoTOC(config.autotoc))
  .use(Permalinks(config.permalinks))
  .use(Layouts(config.layouts))
